// Build the demo library and copy it into the portfolio site (self-contained: the site does not install maze-bot).
//   npm run sync:site [-- ../path/to/site]
// Writes <site>/src/vendor/maze-bot/: maze-bot.js (+ weight chunks), maze-bot.d.ts, types/, SOURCE.txt.
import { execSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const site = resolve(root, process.argv[2] ?? '../malppr.github.io');
if (!existsSync(resolve(site, 'astro.config.mjs'))) throw new Error(`not the site repo: ${site}`);
const run = (cmd) => execSync(cmd, { cwd: root, stdio: 'inherit' });

run('npx vite build --config web/vite.lib.config.ts --logLevel warn');
run('npx tsc -p web/tsconfig.build.json');

const out = resolve(site, 'src/vendor/maze-bot');
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
cpSync(resolve(root, 'web/dist'), out, { recursive: true });
writeFileSync(resolve(out, 'maze-bot.d.ts'), "export * from './types/index';\n");
const commit = execSync('git rev-parse --short HEAD', { cwd: root }).toString().trim();
const dirty = execSync('git status --porcelain -- web presets artifacts/release/versions', { cwd: root }).toString().trim();
writeFileSync(
  resolve(out, 'SOURCE.txt'),
  `Generated by maze-bot (scripts/sync-site.mjs). Do not edit here: change maze-bot and re-run \`npm run sync:site\`.\n` +
    `maze-bot commit: ${commit}${dirty ? ' + uncommitted changes' : ''}\n`,
);
console.log(`synced maze-bot ${commit}${dirty ? ' (dirty)' : ''} -> ${out}`);
